{% set name = "rpaths" %}
{% set version = "0.13" %}
{% set sha256 = "fdb548e6bacc451b6f929d888cc1e79e8f94abae938c5bd69ac367f5c2f95a1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - rpaths

about:
  home: http://github.com/remram44/rpaths
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Path manipulation library'
  description: |
    rpaths is another path manipulation library. It is heavily inspired by
    Unipath and pathlib.

    It aims at total Python 2/3 and Windows/POSIX compatibility. To my
    knowledge, no other library can handle all the possible paths on every
    platform.
  doc_url: http://rpaths.remram.fr/
  dev_url: http://github.com/remram44/rpaths

extra:
  recipe-maintainers:
    - remram44
