{% set name = "rpaths" %}
{% set version = "1.0.0" %}
{% set sha256 = "dd7418b2c837e1b4eb5c5490465d5f282645143e4638c809ddd250dc33395641" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=2.7,<3|>=3.5
    - setuptools
  run:
    - python >=2.7,<3|>=3.5

test:
  imports:
    - rpaths

about:
  home: http://github.com/remram44/rpaths
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Path manipulation library'
  description: |
    rpaths is another path manipulation library. It is heavily inspired by
    Unipath and pathlib.

    It aims at total Python 2/3 and Windows/POSIX compatibility. To my
    knowledge, no other library can handle all the possible paths on every
    platform.
  doc_url: http://rpaths.remram.fr/
  dev_url: http://github.com/remram44/rpaths

extra:
  recipe-maintainers:
    - remram44
