travis:
  secure:
    BINSTAR_TOKEN: XOzC19icyswWArFIWq1a4fpoL3GRKb6FsFzi5NUdq691iL35AHHfeIcgNGdcUysuJ6h+GdJSRnjh+rpEvNBW7Aqr9+R0u9PLnybHfgkJpcKz9h1tnrPFNTjKr8eGhnZMe+Wm1ffTKAdaZdjZLi3fdxmyTJJpqOuAq2WijQqaS4oXJOl/N5W57QvKwszUiLkjcErd/1LVobM4mJeCZjNEJACzExnLhlfaCD2GspUmf8xmHQTpqMaK2DSIYQbTgEgwWSKcFd7eyxT3AM1JTcK1zaWNHDBf4xUTwsopLoCtTDfCyVUwq4rHlz9M+CqlRhUTBbGlUttSzFNXSnxa1r+Ss7/W3yB27zq6Mo7CsTokUHTQufopOvciIZc0Efwnz85F+rz6RCutHknLUb3ZmE0yj79bhR5fYCxhTmaghKyRcy0ZjqR1TJyYweebqMMto9lhDJ+ULKvf2ZWPAiKjpqUA/4IbovtMar24fcc/2DJoSGksMKAftL9Xhq9OFXJ8uOHDg6h+r5GeD89P7EcGRsWElCYI0MDMiu5kxYOoF/cpfOLuHJKZ0+R1XuvgX+w7dFj9csFqrjCSdbd8YwT/9bGRxZTfhPyDRymiIspgiOECGSi851umdSllV8olfLEbm9e2hpig0k1XNQ+o5ebOTnExj2uuPI3GJAGWH7JcYTbSE3E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
