travis:
  secure:
    BINSTAR_TOKEN: OXC3bw6Vw0SC4D6KBUiJZZncZqAjOzcrUivS8HZSD9nOhyV62qO1df3uV0EhESBb2h/Jfbycgu3eFPjtaVCrE6ZzR7UhgrFkYHbfNSh0tJtsgGuhFsxIz24aWpQHfu70jjFrYHiGT81Cdg6jVpwaEKQ0Jzhaw4Caky3lJbuld/1sbVSXpweG3RI01aRIJ5Y8zlpM+OWaTyNlxa6rE5N8FU/WyXJHv3ZXNGquuBm97moOlOTBEc56LiEoTHct+OSOD8uCVzQo/AN3MDhqZwj9dEZvwQE4uCLqe9+H5QK2k/BgDafE11IsavRSQBrii5/EGtQwF3C7WCln97ODfDxNvlWudcnpkunczQRZC5BLeoF3ATI9f19ie9s8Nnv2ujKSjq14+0sr7J4fq+2RujKToRfbhUyMY/609SCQOpyVteYhjw+RL2slDhUfSxqkwrSNodJYESvRQR4DqXZKNvma412hJ0WRvxSCrceGanArzuZ0+OstTsIiJd5VznG+uhe3pkc63+Vb6idO51DdbIooOmXjxC9CwTARht9zItMvwY4AZ34JOLeURom3z3/SDGAfWl3yRUYpkdm9ww5JyQp+27cce3IllVESU9QdoaPdzigf4dbcPxIOspO1sJ4z0XKTPDas0dA6AWg4CKTVdmd7+4y9II2cy/TlQGQMp8fGq7E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
